#!/usr/bin/env python3
"""
Daily API Usage Report - Sends to rayen.kaddechi@esprit.tn
"""
import smtplib
import json
import requests
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# ============ CONFIGURATION ============
EMAIL_FROM = "rayenkaddechi1234@gmail.com"
EMAIL_PASSWORD = "ldgamksnxrbhbeuf"  # Your app password without spaces
EMAIL_TO = "rayen.kaddechi@esprit.tn"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
# =======================================

def get_api_health():
    """Get API health info"""
    try:
        response = requests.get("http://localhost:8000/health", timeout=5)
        return response.json()
    except:
        return {}

def create_report():
    """Create daily report"""
    date = datetime.now().strftime("%Y-%m-%d")
    weekday = datetime.now().strftime("%A")
    
    # Get API health
    health = get_api_health()
    
    # Get model info
    try:
        model_info = requests.get("http://localhost:8000/model/info", timeout=5).json()
        accuracy = f"{float(model_info.get('accuracy', 0))*100:.1f}%" if model_info.get('status') == 'loaded' else "N/A"
    except:
        accuracy = "N/A"
    
    # Create HTML report
    report = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 20px; }}
            .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                     color: white; padding: 30px; border-radius: 10px; text-align: center; }}
            .content {{ margin: 20px; }}
            .card {{ background: white; padding: 20px; margin: 15px 0; border-radius: 10px; 
                   box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
            .highlight {{ background: #e8f5e9; border-left: 5px solid #4CAF50; }}
            .metric {{ font-size: 24px; font-weight: bold; color: #2196F3; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🎯 Breast Cancer Detection API</h1>
            <h2>Daily Performance Report</h2>
            <p>{weekday}, {date}</p>
        </div>
        
        <div class="content">
            <div class="card highlight">
                <h3>📊 Report Summary</h3>
                <p>Hello Rayen, here's your daily API summary sent to your ESPRIT email.</p>
                <p><strong>Current Model Accuracy:</strong> <span class="metric">{accuracy}</span></p>
            </div>
            
            <div class="card">
                <h3>🤖 Model Status</h3>
                <p><strong>Predictions Made (All Time):</strong> {health.get('predictions_made', 0)}</p>
                <p><strong>Model Retrains:</strong> {health.get('retrains_done', 0)}</p>
                <p><strong>API Status:</strong> ✅ {health.get('status', 'unknown').upper()}</p>
                <p><strong>Uptime:</strong> {health.get('uptime_seconds', 0) // 3600} hours</p>
            </div>
            
            <div class="card">
                <h3>🔗 Quick Access Links</h3>
                <ul>
                    <li><a href="http://localhost:8000">🌐 Live API Dashboard</a></li>
                    <li><a href="http://localhost:8000/docs">📚 API Documentation</a></li>
                    <li><a href="http://localhost:9090">📊 Prometheus Metrics</a></li>
                    <li><a href="http://localhost:8000/trending">📈 Performance Trends</a></li>
                </ul>
            </div>
            
            <div style="text-align: center; color: #666; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee;">
                <p>This report was automatically generated by your Breast Cancer Detection API.</p>
                <p>System: WORK Machine | Contact: rayen.kaddechi@esprit.tn</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    return report, date

def send_email(subject, html_content):
    """Send email report"""
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = EMAIL_FROM
    msg['To'] = EMAIL_TO
    
    msg.attach(MIMEText(html_content, 'html'))
    
    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(EMAIL_FROM, EMAIL_PASSWORD)
        server.sendmail(EMAIL_FROM, EMAIL_TO, msg.as_string())
        server.quit()
        print(f"✅ Email sent successfully to: {EMAIL_TO}")
        return True
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        return False

if __name__ == "__main__":
    print(f"📧 Generating daily report for: {EMAIL_TO}")
    
    # Test API connection
    try:
        requests.get("http://localhost:8000/health", timeout=3)
    except:
        print("⚠️  API might not be running. Starting it will provide better data.")
    
    # Create and send report
    report_html, date = create_report()
    subject = f"📊 Breast Cancer API Daily Report - {date}"
    send_email(subject, report_html)
