#!/bin/bash
echo "🔐 Setting up email with provided credentials"
echo "============================================="

# Your credentials
SENDER_EMAIL="rayenkaddechi1234@gmail.com"
SENDER_PASSWORD="ldga mksn xrbh beuf"
RECEIVER_EMAIL="rayen.kaddechi@esprit.tn"

# Clean the password (remove spaces)
CLEAN_PASSWORD=$(echo "$SENDER_PASSWORD" | tr -d ' ')

echo ""
echo "📧 Email Configuration:"
echo "   FROM: $SENDER_EMAIL"
echo "   TO:   $RECEIVER_EMAIL"
echo ""

# ============================================
# 1. CREATE DAILY-REPORT.PY
# ============================================
echo "🔄 Creating daily-report.py..."
cat > daily-report.py << 'PYEOF'
#!/usr/bin/env python3
"""
Daily API Usage Report - Sends to rayen.kaddechi@esprit.tn
"""
import smtplib
import json
import requests
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# ============ CONFIGURATION ============
EMAIL_FROM = "rayenkaddechi1234@gmail.com"
EMAIL_PASSWORD = "ldgamksnxrbhbeuf"  # Your app password without spaces
EMAIL_TO = "rayen.kaddechi@esprit.tn"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
# =======================================

def get_api_health():
    """Get API health info"""
    try:
        response = requests.get("http://localhost:8000/health", timeout=5)
        return response.json()
    except:
        return {}

def create_report():
    """Create daily report"""
    date = datetime.now().strftime("%Y-%m-%d")
    weekday = datetime.now().strftime("%A")
    
    # Get API health
    health = get_api_health()
    
    # Get model info
    try:
        model_info = requests.get("http://localhost:8000/model/info", timeout=5).json()
        accuracy = f"{float(model_info.get('accuracy', 0))*100:.1f}%" if model_info.get('status') == 'loaded' else "N/A"
    except:
        accuracy = "N/A"
    
    # Create HTML report
    report = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 20px; }}
            .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                     color: white; padding: 30px; border-radius: 10px; text-align: center; }}
            .content {{ margin: 20px; }}
            .card {{ background: white; padding: 20px; margin: 15px 0; border-radius: 10px; 
                   box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
            .highlight {{ background: #e8f5e9; border-left: 5px solid #4CAF50; }}
            .metric {{ font-size: 24px; font-weight: bold; color: #2196F3; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🎯 Breast Cancer Detection API</h1>
            <h2>Daily Performance Report</h2>
            <p>{weekday}, {date}</p>
        </div>
        
        <div class="content">
            <div class="card highlight">
                <h3>📊 Report Summary</h3>
                <p>Hello Rayen, here's your daily API summary sent to your ESPRIT email.</p>
                <p><strong>Current Model Accuracy:</strong> <span class="metric">{accuracy}</span></p>
            </div>
            
            <div class="card">
                <h3>🤖 Model Status</h3>
                <p><strong>Predictions Made (All Time):</strong> {health.get('predictions_made', 0)}</p>
                <p><strong>Model Retrains:</strong> {health.get('retrains_done', 0)}</p>
                <p><strong>API Status:</strong> ✅ {health.get('status', 'unknown').upper()}</p>
                <p><strong>Uptime:</strong> {health.get('uptime_seconds', 0) // 3600} hours</p>
            </div>
            
            <div class="card">
                <h3>🔗 Quick Access Links</h3>
                <ul>
                    <li><a href="http://localhost:8000">🌐 Live API Dashboard</a></li>
                    <li><a href="http://localhost:8000/docs">📚 API Documentation</a></li>
                    <li><a href="http://localhost:9090">📊 Prometheus Metrics</a></li>
                    <li><a href="http://localhost:8000/trending">📈 Performance Trends</a></li>
                </ul>
            </div>
            
            <div style="text-align: center; color: #666; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee;">
                <p>This report was automatically generated by your Breast Cancer Detection API.</p>
                <p>System: WORK Machine | Contact: rayen.kaddechi@esprit.tn</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    return report, date

def send_email(subject, html_content):
    """Send email report"""
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = EMAIL_FROM
    msg['To'] = EMAIL_TO
    
    msg.attach(MIMEText(html_content, 'html'))
    
    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(EMAIL_FROM, EMAIL_PASSWORD)
        server.sendmail(EMAIL_FROM, EMAIL_TO, msg.as_string())
        server.quit()
        print(f"✅ Email sent successfully to: {EMAIL_TO}")
        return True
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        return False

if __name__ == "__main__":
    print(f"📧 Generating daily report for: {EMAIL_TO}")
    
    # Test API connection
    try:
        requests.get("http://localhost:8000/health", timeout=3)
    except:
        print("⚠️  API might not be running. Starting it will provide better data.")
    
    # Create and send report
    report_html, date = create_report()
    subject = f"📊 Breast Cancer API Daily Report - {date}"
    send_email(subject, report_html)
PYEOF

chmod +x daily-report.py
echo "✅ Created daily-report.py"

# ============================================
# 2. CREATE ALERTMANAGER CONFIG
# ============================================
echo "🔄 Creating alertmanager.yml..."
cat > alertmanager.yml << 'AMEOF'
global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'rayenkaddechi1234@gmail.com'
  smtp_auth_username: 'rayenkaddechi1234@gmail.com'
  smtp_auth_password: 'ldgamksnxrbhbeuf'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  receiver: 'rayen-alerts'

receivers:
- name: 'rayen-alerts'
  email_configs:
  - to: 'rayen.kaddechi@esprit.tn'
    headers:
      subject: '🚨 [Breast Cancer API Alert] {{ .GroupLabels.alertname }}'
    html: |
      <html>
      <body style="font-family: Arial, sans-serif;">
        <h2 style="color: #e74c3c;">🚨 Breast Cancer API Alert</h2>
        <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
        <p><strong>Time:</strong> {{ .Alerts.0.StartsAt }}</p>
        <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
        <div style="background: #f8f9fa; padding: 15px; margin: 15px 0;">
          <p>Check the API immediately: <a href="http://localhost:8000">http://localhost:8000</a></p>
          <p>View metrics: <a href="http://localhost:9090">http://localhost:9090</a></p>
        </div>
        <p style="color: #666; font-size: 12px;">
          Sent to: rayen.kaddechi@esprit.tn<br>
          System: Breast Cancer Detection API
        </p>
      </body>
      </html>
    send_resolved: true
AMEOF
echo "✅ Created alertmanager.yml"

# ============================================
# 3. CREATE TEST SCRIPT
# ============================================
echo "🔄 Creating test script..."
cat > test-email-now.py << 'TESTEOF'
#!/usr/bin/env python3
"""
Test email with actual credentials
"""
import smtplib
from email.mime.text import MIMEText
from datetime import datetime

print("🔧 Testing email configuration with real credentials")
print("=" * 50)

sender = "rayenkaddechi1234@gmail.com"
password = "ldgamksnxrbhbeuf"  # No spaces
receiver = "rayen.kaddechi@esprit.tn"

print(f"FROM: {sender}")
print(f"TO:   {receiver}")
print("")

try:
    # Test SMTP connection
    print("1. Testing SMTP connection...")
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    
    print("2. Testing login...")
    server.login(sender, password)
    print("   ✅ Login SUCCESSFUL!")
    
    # Send test email
    print("3. Sending test email...")
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    message = f"""Hello Rayen,

This is a test email from your Breast Cancer Detection API system.

✅ Email configuration is working correctly!
✅ Daily reports will be sent to your ESPRIT email
✅ Alerts will arrive when API has issues

Time: {current_time}
System: Breast Cancer API Monitoring
From: {sender}
To: {receiver}

You can now run:
python3 daily-report.py    # Send daily report
./setup-cron.sh           # Schedule daily emails at 8 AM

Your system is ready! 🎉
"""
    
    msg = MIMEText(message)
    msg['Subject'] = '✅ Breast Cancer API - Email Setup Successful!'
    msg['From'] = sender
    msg['To'] = receiver
    
    server.sendmail(sender, receiver, msg.as_string())
    server.quit()
    
    print("✅ Test email SENT successfully!")
    print(f"📧 Check your inbox: {receiver}")
    print("")
    print("🎉 Email setup is COMPLETE!")
    print("")
    print("🚀 Next steps:")
    print("   1. Check your ESPRIT email for the test email")
    print("   2. Run: python3 daily-report.py  (send first report)")
    print("   3. Run: ./setup-cron.sh   (schedule daily emails)")
    
except Exception as e:
    print(f"❌ ERROR: {str(e)}")
    print("")
    print("🔧 Troubleshooting:")
    print("   1. Verify the password is correct (16 characters, no spaces)")
    print("   2. Check if 2-Step Verification is enabled")
    print("   3. Try generating a new app password at:")
    print("      https://myaccount.google.com/apppasswords")
    print("   4. Make sure 'Less secure app access' is NOT enabled")
TESTEOF

chmod +x test-email-now.py
echo "✅ Created test-email-now.py"

# ============================================
# 4. CREATE CRON SETUP SCRIPT
# ============================================
echo "🔄 Creating cron setup script..."
cat > setup-cron.sh << 'CRONEOF'
#!/bin/bash
echo "⏰ Setting up scheduled emails..."
echo ""

# Add daily report at 8:00 AM
(crontab -l 2>/dev/null | grep -v "daily-report.py"; echo "0 8 * * * cd /home/rayen/breast-cancer-app && /home/rayen/breast-cancer-app/venv/bin/python3 /home/rayen/breast-cancer-app/daily-report.py") | crontab -

echo "✅ Daily email scheduled for 8:00 AM"
echo ""
echo "📋 Current scheduled jobs:"
echo "=========================="
crontab -l
echo ""
echo "📧 Emails will be sent to: rayen.kaddechi@esprit.tn"
echo "⏰ Time: Every day at 8:00 AM"
CRONEOF

chmod +x setup-cron.sh
echo "✅ Created setup-cron.sh"

# ============================================
# 5. CREATE SIMPLE TEST (NO EMAIL REQUIRED)
# ============================================
echo "🔄 Creating simple test script..."
cat > quick-test.py << 'QUICKEOF'
#!/usr/bin/env python3
"""
Quick test without sending email
"""
import smtplib

print("🔧 Quick SMTP Test")
print("=" * 40)

try:
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login("rayenkaddechi1234@gmail.com", "ldgamksnxrbhbeuf")
    print("✅ SUCCESS: Credentials are valid!")
    print("✅ Email will work correctly")
    server.quit()
except smtplib.SMTPAuthenticationError:
    print("❌ FAILED: Invalid credentials")
    print("   Check your App Password")
except Exception as e:
    print(f"❌ ERROR: {e}")
QUICKEOF

chmod +x quick-test.py
echo "✅ Created quick-test.py"

echo ""
echo "========================================"
echo "✅ SETUP COMPLETE!"
echo "========================================"
echo ""
echo "📁 Files created:"
echo "   1. daily-report.py     - Daily email report script"
echo "   2. alertmanager.yml    - Alert configuration"
echo "   3. test-email-now.py   - Test email script"
echo "   4. setup-cron.sh      - Schedule daily emails"
echo "   5. quick-test.py      - Quick credential test"
echo ""
echo "🚀 To test immediately:"
echo "   1. Run: python3 quick-test.py"
echo "   2. Run: python3 test-email-now.py"
echo "   3. Check rayen.kaddechi@esprit.tn inbox"
echo ""
echo "📅 To schedule daily emails at 8 AM:"
echo "   Run: ./setup-cron.sh"
echo ""
echo "📧 All emails will be sent FROM: rayenkaddechi1234@gmail.com"
echo "                   TO: rayen.kaddechi@esprit.tn"
echo ""
